In [1]:
import re

import numpy as np

In [2]:
bibfile = 'export.bib'
# bibファイル読み込み
# 改行コードを変更しない(newline='')
with open(bibfile, mode='r', encoding='UTF-8', newline='') as f:
    bibData = f.read()

In [3]:
bibData[:1000]

'@article{RefWorks:RefID:208-1965self-consistent,\n\tauthor={Walter Kohn and Lu Jeu Sham},\n\tyear={1965},\n\ttitle={Self-Consistent Equations Including Exchange and Correlation Effects},\n\tjournal={Physical Review},\n\tvolume={140},\n\tnumber={4A},\n\tpages={A1133},\n\tnote={Kohn-Sham法の原著論文},\n\turl={https://doi.org/10.1103/PhysRev.140.A1133},\n\tdoi={10.1103/PhysRev.140.A1133}\n}\n@book{RefWorks:RefID:207-常田貴夫2012密度汎関数法の基礎,\n\tauthor={常田貴夫},\n\tyear={2012},\n\tmonth={Apr},\n\ttitle={密度汎関数法の基礎 = Fundamentals of Density Functional Theory},\n\tpublisher={講談社},\n\taddress={Tokyo},\n\tedition={1},\n\tnote={DFTについて},\n\tisbn={4061532804}\n}\n@book{RefWorks:RefID:206-1987新しい量子化学,\n\tauthor={Attila Szabo and Neil S. Ostlund},\n\tyear={1987},\n\tmonth={Jul},\n\ttitle={新しい量子化学 : 電子構造の理論入門 上},\n\tpublisher={東京大学出版会},\n\taddress={Tokyo},\n\tedition={1},\n\tnote={Hartree-Fockに詳しい},\n\tisbn={4130621114}\n}\n@article{RefWorks:RefID:205-imai2005water,\n\tauthor={Takashi Imai and Ryusuke Hiraoka and

In [4]:
bibData = re.sub('\n', '', re.sub('\t','',bibData))
bibData[:1000]

'@article{RefWorks:RefID:208-1965self-consistent,author={Walter Kohn and Lu Jeu Sham},year={1965},title={Self-Consistent Equations Including Exchange and Correlation Effects},journal={Physical Review},volume={140},number={4A},pages={A1133},note={Kohn-Sham法の原著論文},url={https://doi.org/10.1103/PhysRev.140.A1133},doi={10.1103/PhysRev.140.A1133}}@book{RefWorks:RefID:207-常田貴夫2012密度汎関数法の基礎,author={常田貴夫},year={2012},month={Apr},title={密度汎関数法の基礎 = Fundamentals of Density Functional Theory},publisher={講談社},address={Tokyo},edition={1},note={DFTについて},isbn={4061532804}}@book{RefWorks:RefID:206-1987新しい量子化学,author={Attila Szabo and Neil S. Ostlund},year={1987},month={Jul},title={新しい量子化学 : 電子構造の理論入門 上},publisher={東京大学出版会},address={Tokyo},edition={1},note={Hartree-Fockに詳しい},isbn={4130621114}}@article{RefWorks:RefID:205-imai2005water,author={Takashi Imai and Ryusuke Hiraoka and Andriy Kovalenko and Fumio Hirata},year={2005},month={Nov 9,},title={Water Molecules in a Protein Cavity Detected by a Statisti

In [5]:
def findIndexes(string, obj):
    indexList = []
    start = 0
    while True:
        i = string.find(obj, start)
        if i == -1:
            break
        indexList.append(i)
        start = i+1
    return indexList
leftbraceIndexList = findIndexes(bibData, '{')
rightbraceIndexList = findIndexes(bibData, '}')
leftbraceIndexList[:20]

[8,
 55,
 90,
 103,
 182,
 207,
 220,
 231,
 244,
 266,
 314,
 347,
 392,
 404,
 417,
 429,
 495,
 509,
 525,
 534]

In [6]:
rightbraceIndexList[:20]

[83,
 95,
 172,
 198,
 211,
 223,
 237,
 260,
 308,
 340,
 341,
 397,
 409,
 421,
 483,
 499,
 515,
 527,
 542,
 560]

In [7]:
nestLevel = np.zeros(len(bibData), dtype=np.int32)
for i in leftbraceIndexList:
    nestLevel[i:] += 1
for i in rightbraceIndexList:
    nestLevel[i:] -= 1
nestLevel

array([0, 0, 0, ..., 2, 1, 0])

In [8]:
nestLevel[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
rightbraceNestLevel = nestLevel[rightbraceIndexList]
rightbraceRootLevelIndexList = np.array(rightbraceIndexList)[np.where(rightbraceNestLevel == 0)[0]]
rightbraceRootLevelIndexList

array([   341,    561,    784,   1777,   3123,   4511,   6117,   7815,
         9859,  12194,  12449,  12693,  13536,  13754,  14084,  16139,
        16344,  16494,  18242,  18402,  18800,  18961,  19409,  19818,
        20206,  21146,  21297,  21449,  23299,  24667,  25098,  26232,
        26662,  28445,  29801,  32256,  34021,  35778,  36212,  37451,
        38314,  39618,  41229,  43157,  44600,  46927,  47105,  47249,
        48094,  48223,  48436,  49678,  51023,  53562,  54850,  55025,
        56801,  58118,  60781,  62470,  62578,  64626,  66977,  69788,
        70022,  70332,  72074,  74152,  74495,  75603,  77202,  79172,
        79544,  81706,  83754,  85193,  85393,  86429,  88142,  88308,
        89431,  90588,  91841,  92373,  92522,  92823,  94705,  97324,
        99352, 101445, 103819, 104749, 105138, 105448, 105863, 106340,
       106874, 107390, 107814, 108274, 108401, 108841, 109076, 109294,
       109498, 110750, 111279, 111503, 113322, 113848, 114861, 115261,
      

In [10]:
start = 0
for i in range(5):
    end = rightbraceRootLevelIndexList[i]+1
    print(bibData[start:end])
    print('----------------------------')
    start = end

@article{RefWorks:RefID:208-1965self-consistent,author={Walter Kohn and Lu Jeu Sham},year={1965},title={Self-Consistent Equations Including Exchange and Correlation Effects},journal={Physical Review},volume={140},number={4A},pages={A1133},note={Kohn-Sham法の原著論文},url={https://doi.org/10.1103/PhysRev.140.A1133},doi={10.1103/PhysRev.140.A1133}}
----------------------------
@book{RefWorks:RefID:207-常田貴夫2012密度汎関数法の基礎,author={常田貴夫},year={2012},month={Apr},title={密度汎関数法の基礎 = Fundamentals of Density Functional Theory},publisher={講談社},address={Tokyo},edition={1},note={DFTについて},isbn={4061532804}}
----------------------------
@book{RefWorks:RefID:206-1987新しい量子化学,author={Attila Szabo and Neil S. Ostlund},year={1987},month={Jul},title={新しい量子化学 : 電子構造の理論入門 上},publisher={東京大学出版会},address={Tokyo},edition={1},note={Hartree-Fockに詳しい},isbn={4130621114}}
----------------------------
@article{RefWorks:RefID:205-imai2005water,author={Takashi Imai and Ryusuke Hiraoka and Andriy Kovalenko and Fumio Hirata},yea

In [11]:
testbibData = bibData[1778:3124]
testbibData

'@article{RefWorks:RefID:204-palmer2010universal,author={David S. Palmer and Andrey I. Frolov and Ekaterina L. Ratkova and Maxim V. Fedorov},year={2010},month={Dec 15,},title={Towards a universal method for calculating hydration free energies: a 3D reference interaction site model with partial molar volume correction},journal={Journal of physics. Condensed matter},volume={22},number={49},pages={492101},note={3D-RISM/KH?による溶媒和エネルギーは実験値に対して17.3kcal/mol過大評価した。その誤差はモル体積と強い相関があることが示される},abstract={We report a simple universal method to systematically improve the accuracy of hydration free energies calculated using an integral equation theory of molecular liquids, the 3D reference interaction site model. A strong linear correlation is observed between the difference of the experimental and (uncorrected) calculated hydration free energies and the calculated partial molar volume for a data set of 185 neutral organic molecules from different chemical classes. By using the partial molar volume as

In [12]:
testnestLevel = nestLevel[1778:3124]
testnestLevel

array([0, 0, 0, ..., 2, 1, 0])

In [13]:
colonIndexList = findIndexes(testbibData, ',')
colonIndexList

[47,
 139,
 151,
 165,
 167,
 318,
 365,
 377,
 389,
 404,
 485,
 663,
 1069,
 1168,
 1236,
 1253,
 1308]

In [14]:
newlinecolonIndexList = np.array(colonIndexList)[np.where(testnestLevel[colonIndexList] == 1)[0]]
newlinecolonIndexList

array([  47,  139,  151,  167,  318,  365,  377,  389,  404,  485, 1236,
       1253, 1308])

In [15]:
start = 0
for end in newlinecolonIndexList:
    end += 1
    print(testbibData[start:end])
    start = end
print(testbibData[end:])

@article{RefWorks:RefID:204-palmer2010universal,
author={David S. Palmer and Andrey I. Frolov and Ekaterina L. Ratkova and Maxim V. Fedorov},
year={2010},
month={Dec 15,},
title={Towards a universal method for calculating hydration free energies: a 3D reference interaction site model with partial molar volume correction},
journal={Journal of physics. Condensed matter},
volume={22},
number={49},
pages={492101},
note={3D-RISM/KH?による溶媒和エネルギーは実験値に対して17.3kcal/mol過大評価した。その誤差はモル体積と強い相関があることが示される},
abstract={We report a simple universal method to systematically improve the accuracy of hydration free energies calculated using an integral equation theory of molecular liquids, the 3D reference interaction site model. A strong linear correlation is observed between the difference of the experimental and (uncorrected) calculated hydration free energies and the calculated partial molar volume for a data set of 185 neutral organic molecules from different chemical classes. By using the partial molar 

In [16]:
dataline = []
start = 0
for end in newlinecolonIndexList:
    dataline.append(testbibData[start:end])
    start = end + 1 
dataline.append(testbibData[start:-1])
# start と -1が同じ位置になる場合(***},}等、最後に不正に','が入っていた場合、空文字になる)
# -> 後で取り除く(dataline分割よりも先に取り除いてもいいかも)
dataline

['@article{RefWorks:RefID:204-palmer2010universal',
 'author={David S. Palmer and Andrey I. Frolov and Ekaterina L. Ratkova and Maxim V. Fedorov}',
 'year={2010}',
 'month={Dec 15,}',
 'title={Towards a universal method for calculating hydration free energies: a 3D reference interaction site model with partial molar volume correction}',
 'journal={Journal of physics. Condensed matter}',
 'volume={22}',
 'number={49}',
 'pages={492101}',
 'note={3D-RISM/KH?による溶媒和エネルギーは実験値に対して17.3kcal/mol過大評価した。その誤差はモル体積と強い相関があることが示される}',
 'abstract={We report a simple universal method to systematically improve the accuracy of hydration free energies calculated using an integral equation theory of molecular liquids, the 3D reference interaction site model. A strong linear correlation is observed between the difference of the experimental and (uncorrected) calculated hydration free energies and the calculated partial molar volume for a data set of 185 neutral organic molecules from different chemical clas

In [17]:
key, item = dataline[10].split('=', 1)
key

'abstract'

In [18]:
item

'{We report a simple universal method to systematically improve the accuracy of hydration free energies calculated using an integral equation theory of molecular liquids, the 3D reference interaction site model. A strong linear correlation is observed between the difference of the experimental and (uncorrected) calculated hydration free energies and the calculated partial molar volume for a data set of 185 neutral organic molecules from different chemical classes. By using the partial molar volume as a linear empirical correction to the calculated hydration free energy, we obtain predictions of hydration free energies in excellent agreement with experiment (R = 0.94, σ = 0.99\xa0kcal\xa0mol (- 1) for a test set of 120 organic molecules).}'