In [1]:
import re

import numpy as np

In [2]:
bibfile = 'export.bib'
# bibファイル読み込み
# 改行コードを変更しない(newline='')
with open(bibfile, mode='r', encoding='UTF-8', newline='') as f:
    bibData = f.read()

In [3]:
bibData[:1000]

'@article{RefWorks:RefID:170-isegawa2016ionization,\r\n\tauthor={Miho Isegawa and Frank Neese and Dimitrios A. Pantazis},\r\n\tyear={2016},\r\n\tmonth={May 10,},\r\n\ttitle={Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches},\r\n\tjournal={Journal of chemical theory and computation},\r\n\tvolume={12},\r\n\tnumber={5},\r\n\tpages={2272-2284},\r\n\tisbn={1549-9618},\r\n\turl={http://dx.doi.org/10.1021/acs.jctc.6b00252},\r\n\tdoi={10.1021/acs.jctc.6b00252},\r\n\tpmid={27065224}\r\n}\r\n@article{RefWorks:RefID:169-boruah2017assessment,\r\n\tauthor={Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar},\r\n\tyear={2017},\r\n\tmonth={Apr 28,},\r\n\ttitle={Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy},\r\n\tjournal={The Journal of chemical physic

In [4]:
bibData = re.sub('\r', '', re.sub('\n', '', re.sub('\t','',bibData)))
bibData[:1000]

'@article{RefWorks:RefID:170-isegawa2016ionization,author={Miho Isegawa and Frank Neese and Dimitrios A. Pantazis},year={2016},month={May 10,},title={Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches},journal={Journal of chemical theory and computation},volume={12},number={5},pages={2272-2284},isbn={1549-9618},url={http://dx.doi.org/10.1021/acs.jctc.6b00252},doi={10.1021/acs.jctc.6b00252},pmid={27065224}}@article{RefWorks:RefID:169-boruah2017assessment,author={Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar},year={2017},month={Apr 28,},title={Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy},journal={The Journal of chemical physics},volume={146},number={16},pages={164102},isbn={0021-9606},url={http://dx.doi.org/10.1063/1.4981529},doi={10.

In [5]:
def findIndexes(string, obj):
    indexList = []
    start = 0
    while True:
        i = string.find(obj, start)
        if i == -1:
            break
        indexList.append(i)
        start = i+1
    return indexList
leftbraceIndexList = findIndexes(bibData, '{')
rightbraceIndexList = findIndexes(bibData, '}')
leftbraceIndexList[:20]

[8,
 57,
 119,
 132,
 148,
 312,
 364,
 376,
 386,
 403,
 419,
 468,
 500,
 519,
 567,
 670,
 683,
 699,
 858,
 899]

In [6]:
rightbraceIndexList[:20]

[112,
 124,
 140,
 302,
 355,
 367,
 378,
 396,
 413,
 462,
 493,
 509,
 510,
 663,
 675,
 691,
 848,
 890,
 903,
 915]

In [7]:
nestLevel = np.zeros(len(bibData), dtype=np.int32)
for i in leftbraceIndexList:
    nestLevel[i:] += 1
for i in rightbraceIndexList:
    nestLevel[i:] -= 1
nestLevel

array([0, 0, 0, ..., 2, 1, 0])

In [8]:
nestLevel[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
rightbraceNestLevel = nestLevel[rightbraceIndexList]
rightbraceRootLevelIndexList = np.array(rightbraceIndexList)[np.where(rightbraceNestLevel == 0)[0]]
rightbraceRootLevelIndexList

array([  510,  1030,  1472,  1818,  2272,  2670,  4021,  4467,  4904,
        5264,  5734,  5912,  6041,  6380,  6483,  6660,  7072,  7498,
        7964,  8406,  8547,  9027,  9389,  9823, 10239, 10393, 10814,
       11245, 11683, 11887, 12168, 12637, 13083, 13379, 14573, 15048,
       15555, 15966, 16411, 16908, 17387, 17561, 17938, 18412, 18560,
       19131, 19593, 20080, 20559, 20682, 20947, 21366, 21918, 22311,
       22776, 23245, 23611, 23963, 24251, 24639, 25102, 25603, 26088,
       26494, 26924, 27051, 27464, 27699, 27901, 28075, 28427, 28878,
       29086, 29439, 29917, 30323, 30706, 31031, 31505, 31574, 32098,
       32481, 32638, 33068, 33446, 33915, 34366, 34782, 35224, 35664,
       36097, 36648, 37148, 37363, 37549, 38002, 38537, 38878, 39391,
       39698, 40347, 40596, 41017, 41411, 41856, 42381, 42786, 43393,
       43902, 44374, 44714, 45221, 45656, 46183, 46627, 46815, 47227,
       47588, 48147, 48578, 49074, 49560, 50028, 50831, 51192, 51578,
       52068, 52612,

In [10]:
start = 0
for i in range(5):
    end = rightbraceRootLevelIndexList[i]+1
    print(bibData[start:end])
    print('----------------------------')
    start = end

@article{RefWorks:RefID:170-isegawa2016ionization,author={Miho Isegawa and Frank Neese and Dimitrios A. Pantazis},year={2016},month={May 10,},title={Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches},journal={Journal of chemical theory and computation},volume={12},number={5},pages={2272-2284},isbn={1549-9618},url={http://dx.doi.org/10.1021/acs.jctc.6b00252},doi={10.1021/acs.jctc.6b00252},pmid={27065224}}
----------------------------
@article{RefWorks:RefID:169-boruah2017assessment,author={Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar},year={2017},month={Apr 28,},title={Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy},journal={The Journal of chemical physics},volume={146},number={16},pages={164102},isbn={0021-9606},url={http://dx.doi.or

In [11]:
def __convertBibEntryToDict(entryStr, nestLevel):
    if len(entryStr) != len(nestLevel):
        raise ValueError('lengths of two arrays didnot match.')
    
    commaIndexList = findIndexes(entryStr, ',')
    newlinecommaIndexList = np.array(commaIndexList)[np.where(nestLevel[commaIndexList] == 1)[0]]
    linedata = []
    start = 0
    for end in newlinecommaIndexList:
        linedata.append(entryStr[start:end])
        start = end + 1 
    linedata.append(entryStr[start:-1])
    # start と -1が同じ位置になる場合(***},}等、最後に余計に','が入っていた場合、空文字になる)
    # -> 後で取り除く
    """linedata==
    ['@article{RefWorks:RefID:204-palmer2010universal',
     'author={David S. Palmer and Andrey I. Frolov and Ekaterina L. Ratkova and Maxim V. Fedorov}',
     'year={2010}',
     'month={Dec 15,}',
     'title={Towards a universal method for calculating hydration free energies: a 3D reference interaction site model with partial molar volume correction}',
     'journal={Journal of physics. Condensed matter}',
     'volume={22}',
     'number={49}',
     'pages={492101}',
     'note={3D-RISM/KH?による溶媒和エネルギーは実験値に対して17.3kcal/mol過大評価した。その誤差はモル体積と強い相関があることが示される}',
     'abstract={We report a simple universal method to systematically improve the accuracy of hydration free energies calculated using an integral equation theory of molecular liquids, the 3D reference interaction site model. A strong linear correlation is observed between the difference of the experimental and (uncorrected) calculated hydration free energies and the calculated partial molar volume for a data set of 185 neutral organic molecules from different chemical classes. By using the partial molar volume as a linear empirical correction to the calculated hydration free energy, we obtain predictions of hydration free energies in excellent agreement with experiment (R = 0.94, σ = 0.99\xa0kcal\xa0mol (- 1) for a test set of 120 organic molecules).}',
     'isbn={0953-8984}',
     'url={http://iopscience.iop.org/0953-8984/22/49/492101}',
     'doi={10.1088/0953-8984/22/49/492101}']
    """
    # 1行目は'{'でsplit
    # 2行目以降は'='でsplit
    # 行頭、行末、区切り文字前後の空白は取り除いておく
    splitlinedata = [0] * len(linedata)
    splitlinedata[0] = re.split(' *{ *', re.sub('^ +','', re.sub(' +$','', linedata[0])))
    for i in range(1, len(linedata)):
        # サイズ2固定でsplit
        splitlinedata[i] = re.split(' *= *', re.sub('^ +','', re.sub(' +$','', linedata[i])), 1)
    
    # チェック
    # 1行目は
    # - 2要素でなければならない
    # - 1要素目は'@'から始まらなければならない
    # 2行目以降は
    # - 2要素が正常
    # - 1要素の場合空文字(もしくは空白文字の連続(ただしsplit時に空文字に変換済み))でなければならない(その場合はlistから除外する)
    dropList = []
    for i, l in enumerate(splitlinedata):
        if i == 0:
            if len(l) != 2:
                raise ValueError('not 2 elements')
            if not l[0].startswith('@'):
                raise ValueError('not start with @')
        else:
            if len(l) == 2:
                continue
            elif len(l) == 1:
                if l[0] == '':
                    dropList.append(i)
                else:
                    raise ValueError('failed to parse: {}'.format(l[0]))
            else:
                # 基本的にあり得ない(split('=',1)のため)
                pass
    
    # 空文字の行は除去
    splitlinedata = [l for i,l in enumerate(splitlinedata) if i not in dropList]
    # 1行目の'@'を除去
    splitlinedata[0][0] = splitlinedata[0][0][1:]
    
    # 辞書型に変換
    entryDict = dict(splitlinedata[1:])
    entryDict['entry'] = splitlinedata[0][0]
    entryDict['id'] = splitlinedata[0][1]
    
    return entryDict
    
def convertBibDataToBibEntryList():
    entryList = []
    start = 0
    for end in rightbraceRootLevelIndexList:
        end += 1
        __bibData = bibData[start:end]
        __nestLevel = nestLevel[start:end]
        entryList.append(__convertBibEntryToDict(__bibData, __nestLevel))
        start = end
    
    return entryList

In [12]:
entryList = convertBibDataToBibEntryList()

In [13]:
entryList[:5]

[{'author': '{Miho Isegawa and Frank Neese and Dimitrios A. Pantazis}',
  'year': '{2016}',
  'month': '{May 10,}',
  'title': '{Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches}',
  'journal': '{Journal of chemical theory and computation}',
  'volume': '{12}',
  'number': '{5}',
  'pages': '{2272-2284}',
  'isbn': '{1549-9618}',
  'url': '{http://dx.doi.org/10.1021/acs.jctc.6b00252}',
  'doi': '{10.1021/acs.jctc.6b00252}',
  'pmid': '{27065224}',
  'entry': 'article',
  'id': 'RefWorks:RefID:170-isegawa2016ionization'},
 {'author': '{Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar}',
  'year': '{2017}',
  'month': '{Apr 28,}',
  'title': '{Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy}',
  'journal': '{The Journal of chemical physics