In [1]:
import re

import numpy as np

In [2]:
bibfile = 'export.bib'
# bibファイル読み込み
# 改行コードを変更しない(newline='')
with open(bibfile, mode='r', encoding='UTF-8', newline='') as f:
    bibData = f.read()

In [3]:
bibData[:1000]

'@article{RefWorks:RefID:170-isegawa2016ionization,\r\n\tauthor={Miho Isegawa and Frank Neese and Dimitrios A. Pantazis},\r\n\tyear={2016},\r\n\tmonth={May 10,},\r\n\ttitle={Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches},\r\n\tjournal={Journal of chemical theory and computation},\r\n\tvolume={12},\r\n\tnumber={5},\r\n\tpages={2272-2284},\r\n\tisbn={1549-9618},\r\n\turl={http://dx.doi.org/10.1021/acs.jctc.6b00252},\r\n\tdoi={10.1021/acs.jctc.6b00252},\r\n\tpmid={27065224},    \r\n}\r\n@article{RefWorks:RefID:169-boruah2017assessment,\r\n\tauthor={Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar},\r\n\tyear={2017},\r\n\tmonth={Apr 28,},\r\n\ttitle={Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy},\r\n\tjournal={The Journal of chemical p

In [4]:
bibData = re.sub('\r', '', re.sub('\n', '', re.sub('\t','',bibData)))
bibData[:1000]

'@article{RefWorks:RefID:170-isegawa2016ionization,author={Miho Isegawa and Frank Neese and Dimitrios A. Pantazis},year={2016},month={May 10,},title={Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches},journal={Journal of chemical theory and computation},volume={12},number={5},pages={2272-2284},isbn={1549-9618},url={http://dx.doi.org/10.1021/acs.jctc.6b00252},doi={10.1021/acs.jctc.6b00252},pmid={27065224},    }@article{RefWorks:RefID:169-boruah2017assessment,author={Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar},year={2017},month={Apr 28,},title={Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy},journal={The Journal of chemical physics},volume={146},number={16},pages={164102},isbn={0021-9606},url={http://dx.doi.org/10.1063/1.4981529},doi

In [5]:
def findIndexes(string, obj):
    indexList = []
    start = 0
    while True:
        i = string.find(obj, start)
        if i == -1:
            break
        indexList.append(i)
        start = i+1
    return indexList
leftbraceIndexList = findIndexes(bibData, '{')
rightbraceIndexList = findIndexes(bibData, '}')
leftbraceIndexList[:20]

[8,
 57,
 119,
 132,
 148,
 312,
 364,
 376,
 386,
 403,
 419,
 468,
 500,
 524,
 572,
 675,
 688,
 704,
 863,
 904]

In [6]:
rightbraceIndexList[:20]

[112,
 124,
 140,
 302,
 355,
 367,
 378,
 396,
 413,
 462,
 493,
 509,
 515,
 668,
 680,
 696,
 853,
 895,
 908,
 920]

In [7]:
nestLevel = np.zeros(len(bibData), dtype=np.int32)
for i in leftbraceIndexList:
    nestLevel[i:] += 1
for i in rightbraceIndexList:
    nestLevel[i:] -= 1
nestLevel

array([0, 0, 0, ..., 2, 1, 0])

In [8]:
nestLevel[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
rightbraceNestLevel = nestLevel[rightbraceIndexList]
rightbraceRootLevelIndexList = np.array(rightbraceIndexList)[np.where(rightbraceNestLevel == 0)[0]]
rightbraceRootLevelIndexList

array([  515,  1036,  1478,  1824,  2278,  2676,  4027,  4473,  4910,
        5270,  5740,  5918,  6047,  6386,  6489,  6666,  7078,  7504,
        7970,  8412,  8553,  9033,  9395,  9829, 10245, 10399, 10820,
       11251, 11689, 11893, 12174, 12643, 13089, 13385, 14579, 15054,
       15561, 15972, 16417, 16914, 17393, 17567, 17944, 18418, 18566,
       19137, 19599, 20086, 20565, 20688, 20953, 21372, 21924, 22317,
       22782, 23251, 23617, 23969, 24257, 24645, 25108, 25609, 26094,
       26500, 26930, 27057, 27470, 27705, 27907, 28081, 28433, 28884,
       29092, 29445, 29923, 30329, 30712, 31037, 31511, 31580, 32104,
       32487, 32644, 33074, 33452, 33921, 34372, 34788, 35230, 35670,
       36103, 36654, 37154, 37369, 37555, 38008, 38543, 38884, 39397,
       39704, 40353, 40602, 41023, 41417, 41862, 42387, 42792, 43399,
       43908, 44380, 44720, 45227, 45662, 46189, 46633, 46821, 47233,
       47594, 48153, 48584, 49080, 49566, 50034, 50837, 51198, 51584,
       52074, 52618,

In [10]:
start = 0
for i in range(5):
    end = rightbraceRootLevelIndexList[i]+1
    print(bibData[start:end])
    print('----------------------------')
    start = end

@article{RefWorks:RefID:170-isegawa2016ionization,author={Miho Isegawa and Frank Neese and Dimitrios A. Pantazis},year={2016},month={May 10,},title={Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches},journal={Journal of chemical theory and computation},volume={12},number={5},pages={2272-2284},isbn={1549-9618},url={http://dx.doi.org/10.1021/acs.jctc.6b00252},doi={10.1021/acs.jctc.6b00252},pmid={27065224},    }
----------------------------
@article{RefWorks:RefID:169-boruah2017assessment,author={Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar},year={2017},month={Apr 28,},title={Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy},journal={The Journal of chemical physics},volume={146},number={16},pages={164102},isbn={0021-9606},url={http://dx.d

In [11]:
def __convertBibEntryToDict(entryStr, nestLevel):
    if len(entryStr) != len(nestLevel):
        raise ValueError('lengths of two arrays didnot match.')
    
    commaIndexList = findIndexes(entryStr, ',')
    newlinecommaIndexList = np.array(commaIndexList)[np.where(nestLevel[commaIndexList] == 1)[0]]
    linedata = []
    start = 0
    for end in newlinecommaIndexList:
        linedata.append(entryStr[start:end])
        start = end + 1 
    linedata.append(entryStr[start:-1])
    # start と -1が同じ位置になる場合(***},}等、最後に余計に','が入っていた場合、空文字になる)
    # -> 後で取り除く
    """linedata==
    ['@article{RefWorks:RefID:204-palmer2010universal',
     'author={David S. Palmer and Andrey I. Frolov and Ekaterina L. Ratkova and Maxim V. Fedorov}',
     'year={2010}',
     'month={Dec 15,}',
     'title={Towards a universal method for calculating hydration free energies: a 3D reference interaction site model with partial molar volume correction}',
     'journal={Journal of physics. Condensed matter}',
     'volume={22}',
     'number={49}',
     'pages={492101}',
     'note={3D-RISM/KH?による溶媒和エネルギーは実験値に対して17.3kcal/mol過大評価した。その誤差はモル体積と強い相関があることが示される}',
     'abstract={We report a simple universal method to systematically improve the accuracy of hydration free energies calculated using an integral equation theory of molecular liquids, the 3D reference interaction site model. A strong linear correlation is observed between the difference of the experimental and (uncorrected) calculated hydration free energies and the calculated partial molar volume for a data set of 185 neutral organic molecules from different chemical classes. By using the partial molar volume as a linear empirical correction to the calculated hydration free energy, we obtain predictions of hydration free energies in excellent agreement with experiment (R = 0.94, σ = 0.99\xa0kcal\xa0mol (- 1) for a test set of 120 organic molecules).}',
     'isbn={0953-8984}',
     'url={http://iopscience.iop.org/0953-8984/22/49/492101}',
     'doi={10.1088/0953-8984/22/49/492101}']
    """
    # 1行目は'{'でsplit
    # 2行目以降は'='でsplit
    # 行頭、行末、区切り文字前後の空白は取り除いておく
    splitlinedata = [0] * len(linedata)
    splitlinedata[0] = re.split(' *{ *', re.sub('^ +','', re.sub(' +$','', linedata[0])))
    for i in range(1, len(linedata)):
        # サイズ2固定でsplit
        splitlinedata[i] = re.split(' *= *', re.sub('^ +','', re.sub(' +$','', linedata[i])), 1)
    
    # チェック
    # 1行目は
    # - 2要素でなければならない
    # - 1要素目は'@'から始まらなければならない
    # 2行目以降は
    # - 2要素が正常
    # - 1要素の場合空文字(もしくは空白文字の連続(ただしsplit時に空文字に変換済み))でなければならない(その場合はlistから除外する)
    # - 2要素目が'{}'で囲まれている場合は'{}'を外す
    dropList = []
    for i, l in enumerate(splitlinedata):
        if i == 0:
            if len(l) != 2:
                raise ValueError('not 2 elements')
            if not l[0].startswith('@'):
                raise ValueError('not start with @')
        else:
            if len(l) == 2:
                if l[1].startswith('{'):
                    l[1] = l[1][1:-1]
                continue
            elif len(l) == 1:
                if l[0] == '':
                    dropList.append(i)
                else:
                    raise ValueError('failed to parse: {}'.format(l[0]))
            else:
                # 基本的にあり得ない(split('=',1)のため)
                pass
    
    # 空文字の行は除去
    splitlinedata = [l for i,l in enumerate(splitlinedata) if i not in dropList]
    # 1行目の'@'を除去
    splitlinedata[0][0] = splitlinedata[0][0][1:]
    
    # 辞書型に変換
    entryDict = dict(splitlinedata[1:])
    entryDict['entry'] = splitlinedata[0][0]
    entryDict['id'] = splitlinedata[0][1]
    
    return entryDict
    
def convertBibDataToBibEntryList():
    entryList = []
    start = 0
    for end in rightbraceRootLevelIndexList:
        end += 1
        __bibData = bibData[start:end]
        __nestLevel = nestLevel[start:end]
        entryList.append(__convertBibEntryToDict(__bibData, __nestLevel))
        start = end
    
    return entryList

In [12]:
entryList = convertBibDataToBibEntryList()

In [13]:
entryList[:5]

[{'author': 'Miho Isegawa and Frank Neese and Dimitrios A. Pantazis',
  'year': '2016',
  'month': 'May 10,',
  'title': 'Ionization Energies and Aqueous Redox Potentials of Organic Molecules: Comparison of DFT, Correlated ab Initio Theory and Pair Natural Orbital Approaches',
  'journal': 'Journal of chemical theory and computation',
  'volume': '12',
  'number': '5',
  'pages': '2272-2284',
  'isbn': '1549-9618',
  'url': 'http://dx.doi.org/10.1021/acs.jctc.6b00252',
  'doi': '10.1021/acs.jctc.6b00252',
  'pmid': '27065224',
  'entry': 'article',
  'id': 'RefWorks:RefID:170-isegawa2016ionization'},
 {'author': 'Abhijit Boruah and Manash Protim Borpuzari and Yukio Kawashima and Kimihiko Hirao and Rahul Kar',
  'year': '2017',
  'month': 'Apr 28,',
  'title': 'Assessment of range-separated functionals in the presence of implicit solvent: Computation of oxidation energy, reduction energy, and orbital energy',
  'journal': 'The Journal of chemical physics',
  'volume': '146',
  'number':